title: Glenn Ingram
logo: /assets/img/logo.png
description: Cartography, GIS, & Planning Portfolio
sidebar:
  - name: Email
    icon: 
    link: mailto:gi.ingram001@gmail.com
  - name: Twitter
    icon: 
    link: https://twitter.com/_glenningram
  - name: LinkedIn
    icon: 
    link: https://www.linkedin.com/in/glenn-ingram/
theme: jekyll-theme-minimal


