title: Glenn Ingram
logo: /assets/img/logo.png
description: Cartography and GIS Portfolio
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal

Twitter: https://twitter.com/_glenningram
