title: Glenn Ingram
logo: /assets/img/logo.jpg
description: Cartography, GIS, & Planning Portfolio
sidebar:
  - name: Email
    icon: https://glenningram.github.io/favicon.ico
    link: mailto:gi.ingram001@gmail.com
  - name: Twitter
    icon: /assets/img/twitter.png
    link: https://twitter.com/_glenningram
  - name: LinkedIn
    icon: /assets/img/linkedin.png
    link: https://www.linkedin.com/in/glenn-ingram/
theme: jekyll-theme-minimal


